#!/bin/bash

function usage {
cat << 'EOT'

USAGE: runSTRUCTURE max_K iterations mainparams_file extraparams_file output_directory input_file	


# This program will run multiple STRUCTURE jobs for different values of K on a SGE cluster

SPECIFY:

max_K = highest value of K to run STRUCTURE for
iterations = number of iterations per K 	#we suggest at least 10
mainparams = the mainparams file for STRUCTURE 	#inc PATH to file - edit this file to suit your analysis  
extraparams = extraparams file for STRUCTURE 	#edit to your specifications
output_directory = the output directory name
input_file = input STRUCTURE file

IMPORTANT:

make sure the STRUCTURE binary is in your PATH i.e. in ~/.bash_profile
run this from within the directory containing your mainparams, extraparams and input.str files
it will create an output directory for each K containing the results


#Mark Richardson (email m.richardson@deakin.edu.au)


EOT
exit -1
}

if [ "X" = "X$1" ]; then
  echo	
  echo "Missing max K to run STRUCTURE for"; usage; 
fi
if [ "X" = "X$2" ]; then
  echo
  echo "Missing number of iterations per K"; usage;
fi
if [ "X" = "X$3" ]; then
  echo
  echo "Missing mainparams file"; usage; 
fi
if [ "X" = "X$4" ]; then
  echo
  echo "Missing extraparams file"; usage;
fi
if [ "X" = "X$5" ]; then
  echo
  echo "Missing output directory"; usage;
fi
if [ "X" = "X$6" ]; then
  echo
    echo "Missing input file"; usage;
    fi

LIMIT=$(($1-1))  
ITER=$(($2-1))
mp=$3
ep=$4
out=$5
in=$6

echo
echo "Running K for K=1 through K=$1"

a=0
b=0

while [ $a -le "$LIMIT" ];do
	a=$(($a+1))
	echo "Running K=$a"
	b=0
	while [ $b -le "$ITER" ];do
		b=$(($b+1))
		echo '#!/bin/bash' > temp.sh
		echo 'source ~/.bash_profile' >> temp.sh
		echo mkdir $out'_'$a >> temp.sh
		echo structure -m $mp -e $ep -i $in -K $a -o $out'_'$a'/results_'$a'_'$b'.txt' >> temp.sh
		qsub -l qname=Virtual temp.sh 
		#cat temp.sh
		rm temp.sh
	done
	

done 



